name: Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: [ '8.3', '8.2', '8.1', '8.0', '7.4' ]
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Download dependencies
        run: composer install --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit tests
